### ISSUE TITLE
Error while playing JioTv

### ISSUE THREAD

**Issue by svamsikrishna** [botallen/repository.botallen#16]
I am from Singapore and used VPN to connect to india. Certainly I am exited to this JioTV plugin.

I keyed in My Id and password. However I am trying to play the videos but failed to play. the following is what I could find from log. Hope this would help you to let me know if there is anything else that I need to change in settings to make it work.

Thanks,
Vamsi

2020-04-20 10:43:27.659 T:31450  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.jiotv/play/Nick_Hindi?maxq=1200
2020-04-20 10:43:27.663 T:31532  NOTICE: Creating InputStream
2020-04-20 10:43:29.974 T:31534   ERROR: 127.0.0.1 - - [20/Apr/2020 10:43:29] "GET /play/Nick_Hindi/master.m3u8?maxq=1200 HTTP/1.1" 451 -
2020-04-20 10:43:29.976 T:31532   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 451
2020-04-20 10:43:29.976 T:31532   ERROR: CCurlFile::Open failed with code 451 for http://127.0.0.1:48996/play/Nick_Hindi/master.m3u8?maxq=1200:
2020-04-20 10:43:29.976 T:31532   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:48996/play/Nick_Hindi/master.m3u8?maxq=1200
2020-04-20 10:43:29.976 T:31532   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:48996/play/Nick_Hindi/master.m3u8?maxq=1200)
2020-04-20 10:43:29.977 T:31532   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.jiotv/play/Nick_Hindi?maxq=1200]
2020-04-20 10:43:29.977 T:31532  NOTICE: CVideoPlayer::OnExit()
2020-04-20 10:43:29.982 T:31534  NOTICE: [Errno 32] Broken pipe
2020-04-20 10:43:29.982 T:31534   ERROR: 127.0.0.1 - - [20/Apr/2020 10:43:29] "GET /play/Nick_Hindi/master.m3u8?maxq=1200 HTTP/1.1" 500 -
2020-04-20 10:43:29.983 T:31534   ERROR: Traceback (most recent call last):
2020-04-20 10:43:29.983 T:31534   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-04-20 10:43:29.983 T:31534   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-04-20 10:43:29.983 T:31534   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 654, in __init__
2020-04-20 10:43:29.984 T:31534   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 713, in finish
2020-04-20 10:43:29.984 T:31534   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/socket.py", line 283, in close
2020-04-20 10:43:29.984 T:31534   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/socket.py", line 307, in flush
2020-04-20 10:43:29.984 T:31534   ERROR: error: [Errno 32] Broken pipe
2020-04-20 10:43:30.002 T:31450  NOTICE: CVideoPlayer::CloseFile()
2020-04-20 10:43:30.009 T:31450  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-20 10:43:30.009 T:31450  NOTICE: VideoPlayer: finished waiting
2020-04-20 10:43:38.905 T:31450  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.jiotv/play/Sony_Yay_Hindi?maxq=1200
2020-04-20 10:43:38.906 T:31590  NOTICE: Creating InputStream
2020-04-20 10:43:40.824 T:31592   ERROR: 127.0.0.1 - - [20/Apr/2020 10:43:40] "GET /play/Sony_Yay_Hindi/master.m3u8?maxq=1200 HTTP/1.1" 451 -
2020-04-20 10:43:40.825 T:31590   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 451
2020-04-20 10:43:40.825 T:31590   ERROR: CCurlFile::Open failed with code 451 for http://127.0.0.1:48996/play/Sony_Yay_Hindi/master.m3u8?maxq=1200:
2020-04-20 10:43:40.825 T:31590   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://127.0.0.1:48996/play/Sony_Yay_Hindi/master.m3u8?maxq=1200
2020-04-20 10:43:40.825 T:31590   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://127.0.0.1:48996/play/Sony_Yay_Hindi/master.m3u8?maxq=1200)
2020-04-20 10:43:40.826 T:31590   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.jiotv/play/Sony_Yay_Hindi?maxq=1200]
2020-04-20 10:43:40.826 T:31590  NOTICE: CVideoPlayer::OnExit()
2020-04-20 10:43:40.830 T:31592  NOTICE: [Errno 32] Broken pipe
2020-04-20 10:43:40.830 T:31592   ERROR: 127.0.0.1 - - [20/Apr/2020 10:43:40] "GET /play/Sony_Yay_Hindi/master.m3u8?maxq=1200 HTTP/1.1" 500 -
2020-04-20 10:43:40.831 T:31592   ERROR: Traceback (most recent call last):
2020-04-20 10:43:40.831 T:31592   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 596, in process_request_thread
2020-04-20 10:43:40.831 T:31592   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 331, in finish_request
2020-04-20 10:43:40.831 T:31592   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 654, in __init__
2020-04-20 10:43:40.831 T:31592   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/SocketServer.py", line 713, in finish
2020-04-20 10:43:40.831 T:31592   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/socket.py", line 283, in close
2020-04-20 10:43:40.832 T:31592   ERROR:   File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/socket.py", line 307, in flush
2020-04-20 10:43:40.832 T:31592   ERROR: error: [Errno 32] Broken pipe
2020-04-20 10:43:40.849 T:31450  NOTICE: CVideoPlayer::CloseFile()
2020-04-20 10:43:40.852 T:31450  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-20 10:43:40.852 T:31450  NOTICE: VideoPlayer: finished waiting
2020-04-20 10:43:40.927 T:31485   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 451
2020-04-20 10:43:40.928 T:31485   ERROR: CCurlFile::Open failed with code 451 for http://jiotv.catchup.cdn.jio.com/dare_images/shows/2020-04-20/200420872000.jpg:
2020-04-20 10:44:59.082 T:31450  NOTICE: CWinSystemAndroid::DestroyWindow

**Comment by svamsikrishna** [comment]
After I click on "Setup Simple IPTV PVR" from add on settings, the issue is resolved.
